[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Nepal-College-of-Information-Technology/AI-Data-Science-Worksop-2024/blob/main/Practice%20Yourself/Assignment_3.1_NumPy.ipynb)

# NumPy Assignment

This assignment consists of 10 tasks designed to help you practice NumPy operations. The tasks are divided into three levels of difficulty: easy, medium, and challenging.

---

## Easy Tasks:

### **Task 1**: Create a 1D NumPy array with the numbers from 1 to 10 and print it.


In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(arr)


[ 1  2  3  4  5  6  7  8  9 10]


### **Task 2:** Create a 2D NumPy array with 2 rows and 3 columns containing any numbers of your choice.

In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


### **Task 3:** Create an array of zeros with a shape of (4, 4) and print it.

In [5]:
arr = np.zeros((4, 4))

print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Medium-Level Tasks:

### **Task 4:** Create a 1D array with the numbers from 1 to 100, and print the sum and mean of the array.

In [8]:
arr = np.array(range(1, 101))

arr_sum = np.sum(arr)
arr_mean = np.mean(arr)

print("Array:\n",arr)
print("Sum:", arr_sum)
print("Mean:", arr_mean)


Array:
 [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
Sum: 5050
Mean: 50.5


### **Task 5:** Create a 5x5 identity matrix using NumPy.

In [9]:
identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### **Task 6:** Reshape a 1D array of numbers from 1 to 12 into a 3x4 matrix.

In [10]:
arr = np.array(range(1, 13))

reshaped_arr = arr.reshape(3, 4)

print(reshaped_arr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### **Task 7:** Create two 1D arrays with 5 random numbers each and print the result of element-wise addition.

In [13]:
arr1 = np.random.randint(5)
arr2 = np.random.randint(5)

result = arr1 + arr2

print("Array 1:", arr1)
print("Array 2:", arr2)
print("Element-wise addition:", result)


Array 1: 2
Array 2: 2
Element-wise addition: 4


## Challenging Tasks:

### **Task 8:** Generate a 3x3 matrix with random integers between 1 and 100. Print the maximum, minimum, and sum of all the elements.

In [11]:
matrix = np.random.randint(1, 101, size=(3, 3))

max_value = np.max(matrix)
min_value = np.min(matrix)
sum_value = np.sum(matrix)

print("Matrix:")
print(matrix)
print("Maximum value:", max_value)
print("Minimum value:", min_value)
print("Sum of all elements:", sum_value)


Matrix:
[[75 22 17]
 [ 2 72 21]
 [52 52 71]]
Maximum value: 75
Minimum value: 2
Sum of all elements: 384


### **Task 9:** Create a 4x4 matrix and replace all the values in the diagonal with 1 (without using identity matrix functions).

In [22]:
matrix = np.zeros((4, 4))
print(matrix)

for i in range(4):
    matrix[i, i] = 1

print("\n",matrix)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### **Task 10:** Create an array of 100 random numbers and compute the mean, standard deviation, and variance of the array.

In [27]:
array = np.random.randint(1, 1001, size=(10, 10))

mean_value = np.mean(array)
std_deviation = np.std(array)
variance = np.var(array)

print("Array:", array)
print("Mean:", mean_value)
print("Standard Deviation:", std_deviation)
print("Variance:", variance)


Array: [[ 88 300 484   9  60 254 642 558 659 952]
 [ 80 515 562 513 830 703 604 273 596   7]
 [503 814 154 520 160 126 361 414 913 651]
 [117 104 277 794 979  17 911  27 201 270]
 [202 220 328 722 117  76 503 534 652 256]
 [277 694 760 568  59 543 884 164 618 816]
 [972 127 831 177 669 648   7 902 310 378]
 [295  51 889 628  41 868  47 990 953 153]
 [675 734 535 414 604 981 515 520 154 191]
 [587 441 319 813 954 985 909 849 733 913]]
Mean: 487.57
Standard Deviation: 306.0322615346297
Variance: 93655.7451


---